name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala as dependências de Python (incluindo numpy)

      - name: Install Node.js and npm Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Start Flask app
        run: |
          nohup flask run &  # Inicia a aplicação Flask em segundo plano
          sleep 10  # Aguardar 10 segundos para garantir que o servidor esteja rodando
