name: Flask App CI Pipeline

on:
  push:
    branches:
      - main # ou a branch que você usa
  pull_request:
    branches:
      - main # ou a branch que você usa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install numpy with a compatible version
        run: |
          pip install --upgrade numpy==1.21.6

      - name: Run Flask application (in background)
        run: |
          nohup python app.py &

      - name: Test Flask app is running
        run: |
          curl -s http://127.0.0.1:5000 || echo "Flask is not accessible"

      - name: Run tests
        run: |
          pytest tests/  # ou o comando que você usar para rodar seus testes

      - name: Shutdown Flask app
        run: |
          kill $(lsof -t -i:5000)  # Para matar o processo Flask após os testes
