name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libatlas-base-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade numpy==1.21.6

      - name: Install Node.js and npm Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Start Flask app
        run: |
          FLASK_APP=app.py FLASK_ENV=development flask run &  # Subir o Flask em segundo plano
          sleep 10  # Esperar 10 segundos para garantir que a aplicação subiu corretamente
