name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app
        run: |
          python train_model.py
          nohup python app.py &

      - name: Run performance benchmark
        run: python unit/performance_benchmark.py

      - name: Run inference quality benchmark
        run: python unit/evaluate_model.py

      - name: Install npm Dependencies
        run: |
          npm install
        working-directory: ./tests/e2e

      - name: Run Cypress Tests
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: http://127.0.0.1:5000
        working-directory: ./tests/e2e

      - name: Validate Inference Quality
        run: python scripts/validate_inference.py
        env:
          MODEL_ENDPOINT: http://127.0.0.1:5000
