name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify requirements.txt exists
        run: |
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js and npm Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install npm Dependencies
        run: |
          npm install
        working-directory: .

      - name: Install Cypress
        uses: cypress-io/github-action@v4
        with:
          install: true

      - name: Start the App
        run: python app.py &
        env:
          FLASK_ENV: development

      - name: Wait for the App
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:5000 > /dev/null; then
              echo "App is ready!"
              break
            fi
            echo "Waiting for the app to start..."
            sleep 5
          done

      - name: Run Cypress Tests
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: http://127.0.0.1:5000
        working-directory: ./cypress_ml

      - name: Validate Inference Quality
        run: python scripts/validate_inference.py
        env:
          MODEL_ENDPOINT: http://127.0.0.1:5000
